; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:seeed_xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = espidf

; --- New Environment For Google Test Desktop execution ---
[env:desktop]
platform = native
test_framework = googletest
extra_scripts = pre:force_path.py
build_flags = 
    -std=c++20
    -pthread
    -static
    -static-libgcc
    -static-libstdc++
    -I test              
    -I lib/Gpio              
    -I lib/RotaryEncoder
    -I lib/MenuEngine